/* Shared Tailwind (Play CDN) config for every page.
   Loaded right after the CDN script so all pages use the same design tokens. */
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Themed tokens read from CSS variables (channel form so opacity
        // modifiers like bg-background/50 still work). Dark/light values are
        // defined in css/styles.css. Unused Material tokens stay as hex.
        background: "rgb(var(--c-background) / <alpha-value>)",
        surface: "rgb(var(--c-surface) / <alpha-value>)",
        "surface-dim": "#141313",
        "surface-bright": "#3a3939",
        "surface-variant": "rgb(var(--c-surface-variant) / <alpha-value>)",
        "surface-tint": "#c6c6c7",
        "surface-container-lowest": "rgb(var(--c-surface-container-lowest) / <alpha-value>)",
        "surface-container-low": "rgb(var(--c-surface-container-low) / <alpha-value>)",
        "surface-container": "rgb(var(--c-surface-container) / <alpha-value>)",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353434",
        "on-background": "rgb(var(--c-on-background) / <alpha-value>)",
        "on-surface": "rgb(var(--c-on-surface) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--c-on-surface-variant) / <alpha-value>)",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        outline: "rgb(var(--c-outline) / <alpha-value>)",
        "outline-variant": "rgb(var(--c-outline-variant) / <alpha-value>)",
        line: "rgb(var(--c-line) / <alpha-value>)",
        primary: "rgb(var(--c-primary) / <alpha-value>)",
        "on-primary": "rgb(var(--c-on-primary) / <alpha-value>)",
        "primary-container": "#e2e2e2",
        "on-primary-container": "#636565",
        "primary-fixed": "rgb(var(--c-primary-fixed) / <alpha-value>)",
        "primary-fixed-dim": "rgb(var(--c-primary-fixed-dim) / <alpha-value>)",
        "on-primary-fixed": "#1a1c1c",
        "on-primary-fixed-variant": "#454747",
        "inverse-primary": "#5d5f5f",
        secondary: "#c9c6c5",
        "on-secondary": "#313030",
        "secondary-container": "rgb(var(--c-secondary-container) / <alpha-value>)",
        "on-secondary-container": "#bab8b7",
        "secondary-fixed": "#e5e2e1",
        "secondary-fixed-dim": "#c9c6c5",
        "on-secondary-fixed": "#1c1b1b",
        "on-secondary-fixed-variant": "#474646",
        tertiary: "#ffffff",
        "on-tertiary": "#303030",
        "tertiary-container": "#e4e2e1",
        "on-tertiary-container": "#656464",
        "tertiary-fixed": "#e4e2e1",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-tertiary-fixed": "#1b1c1c",
        "on-tertiary-fixed-variant": "rgb(var(--c-on-tertiary-fixed-variant) / <alpha-value>)",
        error: "rgb(var(--c-error) / <alpha-value>)",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        "section-gap": "160px",
      },
      fontFamily: {
        "display-xl": ["Space Grotesk"],
        "display-xl-mobile": ["Space Grotesk"],
        "headline-lg": ["Space Grotesk"],
        "headline-lg-mobile": ["Space Grotesk"],
        "body-md": ["Inter"],
        "label-mono-sm": ["Space Mono"],
        "label-mono-xs": ["Space Mono"],
      },
      fontSize: {
        "display-xl": ["140px", { lineHeight: "120px", letterSpacing: "-0.04em", fontWeight: "600" }],
        "display-xl-mobile": ["64px", { lineHeight: "60px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "headline-lg-mobile": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "label-mono-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "500" }],
        "label-mono-xs": ["10px", { lineHeight: "14px", letterSpacing: "0.15em", fontWeight: "400" }],
      },
    },
  },
};
